version: '3.8'

services:
  # Note: Nextcloud and its database are pre-installed on this machine
  # This compose file only runs the background processing scripts

  # Data Preprocessing Scripts
  data-processor:
    build:
      context: ./docker/scripts
      dockerfile: Dockerfile
    container_name: adamant-data-processor
    restart: unless-stopped
    environment:
      - PROCESSING_INTERVAL=${PROCESSING_INTERVAL:-3600}
      - NEXTCLOUD_HOST=${NEXTCLOUD_HOST:-localhost}
      - NEXTCLOUD_PORT=${NEXTCLOUD_PORT:-80}
      - NEXTCLOUD_USER=${NEXTCLOUD_USER:-admin}
      - NEXTCLOUD_PASSWORD=${NEXTCLOUD_PASSWORD}
      - NEXTCLOUD_DATA_DIR=${NEXTCLOUD_DATA_DIR:-/var/www/html/data}
    volumes:
      - shared_data:/data
      - ./bin:/app/scripts:ro
      - processor_logs:/app/logs
      - ~/.ssh:/home/app/.ssh:ro
      - ${NEXTCLOUD_DATA_DIR:-/var/www/html/data}:/var/www/html/data:ro
    network_mode: host
    command: >
      bash -c "
        while true; do
          /app/scripts/data_preprocessing.sh
          sleep ${PROCESSING_INTERVAL:-3600}
        done
      "

  # File Watcher for real-time processing
  file-watcher:
    build:
      context: ./docker/scripts
      dockerfile: Dockerfile
    container_name: adamant-file-watcher
    restart: unless-stopped
    environment:
      - WATCH_DIR=/data/raw
      - PROCESSED_DIR=/data/sorted
      - NEXTCLOUD_HOST=${NEXTCLOUD_HOST:-localhost}
      - NEXTCLOUD_PORT=${NEXTCLOUD_PORT:-80}
      - NEXTCLOUD_USER=${NEXTCLOUD_USER:-admin}
      - NEXTCLOUD_PASSWORD=${NEXTCLOUD_PASSWORD}
      - NEXTCLOUD_DATA_DIR=${NEXTCLOUD_DATA_DIR:-/var/www/html/data}
    volumes:
      - shared_data:/data
      - ./bin:/app/scripts:ro
      - watcher_logs:/app/logs
      - ${NEXTCLOUD_DATA_DIR:-/var/www/html/data}:/var/www/html/data:ro
    network_mode: host
    command: >
      bash -c "
        inotifywait -m -r -e create,moved_to /data/raw | while read path action file; do
          echo \"File \$file \$action in \$path\"
          /app/scripts/data_preprocessing.sh
        done
      "

volumes:
  shared_data:
    driver: local
  processor_logs:
    driver: local
  watcher_logs:
    driver: local

