# Build step #1: React
FROM node:16-alpine as build-step

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json package-lock.json ./
COPY ./src ./src
COPY ./public ./public

RUN npm install
RUN npm run build

# Build step #2: Nginx
FROM nginx:stable-alpine

COPY --from=build-step /app/build /usr/share/nginx/html
COPY deployment/nginx.default.prod.conf /etc/nginx/conf.d/default.conf
